services:
  minecraft:
    container_name: minecraft
    image: docker.io/itzg/minecraft-server:stable
    depends_on:
      - seq-input-syslog
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./mcdata:/data:z
      - ./plugins:/plugins:Z
      - ./log4j2.xml:/data/log4j2.xml:Z
    hostname: ${MC_HOST}
    environment:
      ## All flags:
      ## https://docker-minecraft-server.readthedocs.io/en/latest/variables/
      #
      ## Server version
      VERSION: 1.20.6
      TYPE: PAPER
      DIFFICULTY: easy
      #
      ## Performance
      # USE_AIKAR_FLAGS: true
      MAX_MEMORY: 12288M
      JVM_XX_OPTS: "-XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32"
      JVM_DD_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      MAX_PLAYERS: 50
      # VIEW_DISTANCE: 10
      PLAYER_IDLE_TIMEOUT: 10
      # STOP_SERVER_ANNOUNCE_DELAY: 60
      #
      ## Customize
      MOTD: ${MOTD}
      ICON: ${ICON}
      OVERRIDE_ICON: true
      SERVER_NAME: "Minecraft Server"
      #
      ## World
      ENABLE_COMMAND_BLOCK: false
      FORCE_GAMEMODE: true
      SNOOPER_ENABLED: false
      SPAWN_PROTECTION: 6
      SEED: ${SEED}
      MODE: survival
      #
      ## Operator
      OPS: ${OPS}
      BROADCAST_CONSOLE_TO_OPS: false
      BROADCAST_RCON_TO_OPS: false
      RCON_PASSWORD: ${RCON_PASSWORD}
      # https://modrinth.com/plugins
      MODRINTH_PROJECTS: |
        chunky
      # https://www.spigotmc.org/resources/categories/spigot.4/
      # SPIGET_RESOURCES: 8631
      #
      ## Other
      UID: 1000
      GID: 0
      TZ: Asia/Taipei
      ENABLE_ROLLING_LOGS: true
      GUI: false
      EULA: "TRUE"
    deploy:
      resources:
        limits:
          memory: 30G
    # stop_grace_period: 1m30s
    ## Not for podman
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: "tcp://seq.myhost.com:443"
    #     gelf-compression-type: none
    #     tag: minecraft
    #     labels: minecraft

  # # https://github.com/itzg/docker-mc-backup
  # backups:
  #   image: docker.io/itzg/mc-backup
  #   depends_on:
  #     - minecraft
  #   environment:
  #     TZ: Asia/Taipei
  #     BACKUP_INTERVAL: "24h"
  #     RCON_HOST: minecraft
  #     RCON_PASSWORD: ${RCON_PASSWORD}
  #     INITIAL_DELAY: 120
  #     PAUSE_IF_NO_PLAYERS: true
  #     BACKUP_METHOD: restic
  #     RESTIC_VERBOSE: true
  #     RESTIC_PASSWORD: ${MC_HOST}
  #     RESTIC_REPOSITORY: s3:${S3_HOST}/mcbackups
  #     AWS_ACCESS_KEY_ID: mcbackups
  #     AWS_SECRET_ACCESS_KEY: ${MC_HOST}
  #   volumes:
  #     - /mcdata:/data:ro,z
  #     - backups:/backups:z

  # Must setup log4j2.xml to send logs to syslog
  # ref:
  # https://logging.apache.org/log4j/2.x/manual/appenders.html#syslogappender
  # https://docs.datalust.co/docs/syslog
  seq-input-syslog:
    init: true
    image: docker.io/datalust/seq-input-syslog:latest
    # ports:
    #   - "514:514/udp"
    environment:
      SEQ_ADDRESS: ${SEQ_ADDRESS}
      SEQ_API_KEY: ${SEQ_API_KEY}
    restart: unless-stopped
    stop_grace_period: 30s
volumes:
  backups:
